apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: crawler
type: Opaque
stringData:
  DATABASE_URL: "postgresql://crawler:crawler@postgres-postgresql:5432/crawler?schema=public"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: crawler
data:
  REDIS_HOST: "redis-master"
  REDIS_PORT: "6379"
  QUEUE_NAME: "crawl"
  PORT: "3000"
  WORKER_CONCURRENCY: "5"
  HEALTH_PORT: "3001"